name: build

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libxinerama-dev libxrandr-dev libxkbcommon-dev libxcursor-dev libgl1-mesa-dev libglu1-mesa-dev libx11-dev libxi-dev libxxf86vm-dev
    - name: Setup meson
      run: meson setup build
    - name: Build
      run: ninja -C build
    - name: Test
      run: meson test -C build -v
  windows:
    runs-on: windows-latest
    env:
      VCVARSALL: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat"'
      VCARCH: 'x64'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - run: pip install meson ninja
    - name: Setup meson
      shell: cmd
      run: |
        call %VCVARSALL% %VCARCH%
        meson setup build
    - name: Build
      shell: cmd
      run: |
        call %VCVARSALL% %VCARCH%
        ninja -C build
    - name: Test
      shell: cmd
      run: |
        call %VCVARSALL% %VCARCH%
        meson test -C build -v
