name: build

on: [push]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: install dependencies
      run: sudo apt-get install -y libglfw3-dev
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake -G Ninja ..
    - name: ninja
      run: ninja -C build
    - name: ninja test
      run: ninja -C build test
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: cmake
      run: |
        mkdir build
        cd build
        cmake -G Ninja ..
    - name: ninja
      run: ninja -C build
    - name: ninja test
      run: ninja -C build test
